# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of expense', max_length=16)),
                ('percent', models.IntegerField(help_text='percent that the school covers')),
            ],
        ),
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of policy', max_length=16)),
                ('link', models.URLField(blank=True, help_text='link to policy URL/document', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Raiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='first name', max_length=16)),
                ('last_name', models.CharField(help_text='last name', max_length=16)),
                ('phone', models.CharField(help_text='phone number', max_length=16)),
                ('email', models.EmailField(help_text='email address', max_length=64)),
                ('address_1', models.CharField(help_text='address line 1', max_length=32)),
                ('address_2', models.CharField(blank=True, help_text='address line 2', max_length=32, null=True)),
                ('city', models.CharField(help_text='city', max_length=32)),
                ('state', models.CharField(help_text='state', max_length=16)),
                ('country', models.CharField(help_text='country', max_length=16)),
                ('experience', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RaiserSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(max_length=16)),
                ('q2', models.CharField(max_length=16)),
                ('q3', models.CharField(max_length=16)),
                ('q4', models.CharField(max_length=16)),
                ('q5', models.CharField(max_length=16)),
                ('raiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matcher.Raiser')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of service school', max_length=64)),
                ('url', models.URLField(help_text='website', max_length=64)),
                ('address_1', models.CharField(help_text='address line 1', max_length=32)),
                ('address_2', models.CharField(blank=True, help_text='address line 2', max_length=32, null=True)),
                ('city', models.CharField(help_text='city', max_length=32)),
                ('state', models.CharField(help_text='state', max_length=16)),
                ('country', models.CharField(help_text='country', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='first name', max_length=16)),
                ('last_name', models.CharField(help_text='last name', max_length=16)),
                ('phone', models.CharField(help_text='phone number', max_length=16)),
                ('email', models.EmailField(help_text='email address', max_length=64)),
                ('address_1', models.CharField(help_text='address line 1', max_length=32)),
                ('address_2', models.CharField(blank=True, help_text='address line 2', max_length=32, null=True)),
                ('city', models.CharField(help_text='city', max_length=32)),
                ('state', models.CharField(help_text='state', max_length=16)),
                ('country', models.CharField(help_text='country', max_length=16)),
                ('role', models.CharField(help_text='role or title', max_length=16)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matcher.School')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(max_length=16)),
                ('q2', models.CharField(max_length=16)),
                ('q3', models.CharField(max_length=16)),
                ('q4', models.CharField(max_length=16)),
                ('q5', models.CharField(max_length=16)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matcher.School')),
            ],
        ),
        migrations.AddField(
            model_name='policies',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matcher.School'),
        ),
        migrations.AddField(
            model_name='expense',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matcher.School'),
        ),
    ]
